eventos:
    resource: "@EventosBundle/Controller/"
    type:     annotation
    prefix:   /

curso:
    resource: "@CursoBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
