EventosBundle\Entity\Evento:

  type: entity
  table: eventos
  manyToOne:  
    organizator:
      targetEntity: Person
      joinColumn:
        name: organizator_id
        referencedColumnName: id
  id:
    id:
      type: integer
      id: true
      generator:
          strategy: AUTO   
  fields:
    name:
      type: string
      length: 255
    description:
      type: text
    sport:
      type: text
    organizator:
      type: text
      length: 255


 # protected $asssistants;
 # protected $organizator;
 # protected $price;
 # protected $material;
 # protected $date_start;
 # protected $date_end;
